# Generated by Django 3.2.6 on 2021-09-07 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='received',
            name='created_on',
        ),
    ]
