# Generated by Django 3.2.6 on 2021-09-07 11:24

from django.db import migrations, models
import restapi.validators


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0002_remove_received_created_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='received',
            name='file_directory',
            field=models.FileField(default=1, upload_to='received-files/%y-%m-%d/', validators=[restapi.validators.validate_image_extension]),
            preserve_default=False,
        ),
    ]
