# Generated by Django 3.2.6 on 2021-09-07 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0003_alter_received_file_directory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='received',
            name='registry_number',
            field=models.CharField(help_text='File Name. Automatically generated', max_length=8),
        ),
    ]
